version: '3.3'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c listen_addresses='*'
      -c password_encryption=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    shm_size: 128mb

    networks:
      - task-network
    restart: always

  app:
    build: .
    container_name: task_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass123
    depends_on:
      - postgres_db
    networks:
      - task-network
    restart: unless-stopped

volumes:
  postgres_db:

networks:
  task-network:
    driver: bridge